import { useState } from 'react';
import { Code, Copy, Check, ArrowRight } from 'lucide-react';

export default function JsonToGo() {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [structName, setStructName] = useState('AutoGenerated');
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  const [options, setOptions] = useState({
    inlineTypeDefinitions: false,
    omitempty: true,
    allOmitempty: false,
  });

  const capitalize = (s: string): string => {
    return s.charAt(0).toUpperCase() + s.slice(1);
  };

  const toGoName = (name: string): string => {
    // Convert snake_case or kebab-case to PascalCase
    return name
      .split(/[-_]/)
      .map(part => capitalize(part))
      .join('');
  };

  const getGoType = (value: unknown, key: string): string => {
    if (value === null) return 'interface{}';
    
    switch (typeof value) {
      case 'string':
        return 'string';
      case 'number':
        return Number.isInteger(value) ? 'int' : 'float64';
      case 'boolean':
        return 'bool';
      case 'object':
        if (Array.isArray(value)) {
          if (value.length === 0) return '[]interface{}';
          return `[]${getGoType(value[0], key)}`;
        }
        return toGoName(key);
      default:
        return 'interface{}';
    }
  };

  const generateStruct = (obj: Record<string, unknown>, name: string, indent: number = 0): string => {
    const spaces = '  '.repeat(indent);
    let result = `${spaces}type ${name} struct {\n`;
    const nestedStructs: string[] = [];

    for (const [key, value] of Object.entries(obj)) {
      const goName = toGoName(key);
      let goType = getGoType(value, key);
      
      // Handle nested objects
      if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
        nestedStructs.push(generateStruct(value as Record<string, unknown>, goName, indent));
      }
      
      // Handle arrays of objects
      if (Array.isArray(value) && value.length > 0 && typeof value[0] === 'object') {
        const itemName = goName.endsWith('s') ? goName.slice(0, -1) : goName + 'Item';
        goType = `[]${itemName}`;
        nestedStructs.push(generateStruct(value[0] as Record<string, unknown>, itemName, indent));
      }

      // Build JSON tag
      let jsonTag = key;
      if (options.omitempty || options.allOmitempty) {
        jsonTag += ',omitempty';
      }

      result += `${spaces}  ${goName} ${goType} \`json:"${jsonTag}"\`\n`;
    }

    result += `${spaces}}\n`;
    
    // Add nested structs
    if (nestedStructs.length > 0 && !options.inlineTypeDefinitions) {
      result = nestedStructs.join('\n') + '\n' + result;
    }

    return result;
  };

  const convert = () => {
    try {
      const parsed = JSON.parse(input);
      
      if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
        setError('Input must be a JSON object');
        setOutput('');
        return;
      }

      const goStruct = generateStruct(parsed, structName);
      setOutput(goStruct);
      setError('');
    } catch (e) {
      setError((e as Error).message);
      setOutput('');
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const loadSample = () => {
    const sample = {
      "id": 123,
      "name": "SEO Buddy",
      "description": "A powerful SEO tool",
      "is_active": true,
      "price": 29.99,
      "tags": ["seo", "marketing", "tools"],
      "author": {
        "name": "Obaida Siddque Pranto",
        "email": "OSPranto.Official@gmail.com",
        "company": "OSPranto Tech"
      },
      "features": [
        {
          "name": "SEO Checker",
          "enabled": true
        }
      ],
      "created_at": "2024-01-15T10:30:00Z"
    };
    setInput(JSON.stringify(sample, null, 2));
    setOutput('');
    setError('');
  };

  return (
    <div className="p-4 sm:p-6 max-w-6xl mx-auto">
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="p-2 bg-gradient-to-r from-cyan-500 to-blue-500 rounded-lg">
            <Code className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-xl sm:text-2xl font-bold text-gray-800 dark:text-white">JSON to Go Struct</h1>
            <p className="text-sm text-gray-500 dark:text-gray-400">Convert JSON to Go struct definitions</p>
          </div>
        </div>
      </div>

      {/* Options */}
      <div className="bg-white dark:bg-gray-800 rounded-xl p-4 mb-4 shadow-sm border border-gray-200 dark:border-gray-700">
        <div className="flex flex-wrap gap-4 items-center">
          <div className="flex items-center gap-2">
            <label className="text-sm text-gray-600 dark:text-gray-400">Struct Name:</label>
            <input
              type="text"
              value={structName}
              onChange={(e) => setStructName(e.target.value)}
              className="px-3 py-1.5 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-800 dark:text-white"
              placeholder="MyStruct"
            />
          </div>
          <label className="flex items-center gap-2 text-sm">
            <input
              type="checkbox"
              checked={options.omitempty}
              onChange={(e) => setOptions({ ...options, omitempty: e.target.checked })}
              className="w-4 h-4 text-blue-500 rounded"
            />
            <span className="text-gray-700 dark:text-gray-300">Add omitempty</span>
          </label>
          <button onClick={loadSample} className="ml-auto px-4 py-2 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600">
            📋 Sample
          </button>
          <button
            onClick={convert}
            className="px-4 py-2 bg-gradient-to-r from-cyan-500 to-blue-500 text-white rounded-lg font-medium hover:shadow-lg transition-all flex items-center gap-2"
          >
            Convert <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Error */}
      {error && (
        <div className="mb-4 p-4 bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-800 rounded-xl text-red-600 dark:text-red-400">
          ❌ {error}
        </div>
      )}

      {/* Editor */}
      <div className="grid lg:grid-cols-2 gap-4">
        {/* Input */}
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden">
          <div className="px-4 py-3 bg-yellow-50 dark:bg-yellow-900/30 border-b border-gray-200 dark:border-gray-700">
            <span className="font-medium text-yellow-700 dark:text-yellow-400">📥 JSON Input</span>
          </div>
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder='{\n  "name": "example",\n  "value": 123\n}'
            className="w-full h-96 p-4 font-mono text-sm bg-transparent text-gray-800 dark:text-gray-200 resize-none focus:outline-none"
          />
        </div>

        {/* Output */}
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden">
          <div className="flex items-center justify-between px-4 py-3 bg-cyan-50 dark:bg-cyan-900/30 border-b border-gray-200 dark:border-gray-700">
            <span className="font-medium text-cyan-700 dark:text-cyan-400">📤 Go Struct</span>
            {output && (
              <button onClick={copyToClipboard} className="p-1 text-gray-400 hover:text-blue-500">
                {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
              </button>
            )}
          </div>
          <pre className="w-full h-96 p-4 font-mono text-sm text-gray-800 dark:text-gray-200 overflow-auto">
            {output || <span className="text-gray-400">Go struct will appear here...</span>}
          </pre>
        </div>
      </div>

      {/* Go Tips */}
      <div className="mt-6 p-4 bg-cyan-50 dark:bg-cyan-900/20 rounded-xl border border-cyan-200 dark:border-cyan-800">
        <h3 className="font-semibold text-cyan-800 dark:text-cyan-300 mb-2">💡 Go Struct Tips</h3>
        <ul className="text-sm text-cyan-700 dark:text-cyan-400 space-y-1">
          <li>• <code className="bg-cyan-100 dark:bg-cyan-800 px-1 rounded">omitempty</code> - Empty values are omitted during JSON encoding</li>
          <li>• Field names are converted to PascalCase automatically</li>
          <li>• Nested objects become separate struct types</li>
          <li>• Arrays are typed based on the first element</li>
        </ul>
      </div>
    </div>
  );
}
