import { useState } from 'react';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';

export function RobotsTxtGenerator() {
  const [sitemapUrl, setSitemapUrl] = useState('https://example.com/sitemap.xml');
  const [allowAll, setAllowAll] = useState(true);
  const [disallowPaths, setDisallowPaths] = useState(['/admin/', '/private/', '/wp-admin/']);
  const [copied, setCopied] = useState(false);

  const generateRobotsTxt = () => {
    let content = '# Robots.txt generated by SEO Buddy\n';
    content += '# https://seo-buddy.com\n\n';
    content += 'User-agent: *\n';
    
    if (allowAll) {
      content += 'Allow: /\n';
    }
    
    disallowPaths.forEach(path => {
      if (path.trim()) {
        content += `Disallow: ${path}\n`;
      }
    });
    
    content += `\nSitemap: ${sitemapUrl}`;
    
    return content;
  };

  const addPath = () => {
    setDisallowPaths([...disallowPaths, '']);
  };

  const removePath = (index: number) => {
    setDisallowPaths(disallowPaths.filter((_, i) => i !== index));
  };

  const updatePath = (index: number, value: string) => {
    const newPaths = [...disallowPaths];
    newPaths[index] = value;
    setDisallowPaths(newPaths);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generateRobotsTxt());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([generateRobotsTxt()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      <div className="text-center">
        <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold text-gray-900 dark:text-white">
          🤖 Robots.txt Generator
        </h1>
        <p className="text-sm sm:text-base text-gray-600 dark:text-gray-400 mt-2">
          Create a robots.txt file to control how search engines crawl your site
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="p-4 sm:p-6">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">⚙️ Configure</h2>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Sitemap URL
              </label>
              <input
                type="url"
                value={sitemapUrl}
                onChange={(e) => setSitemapUrl(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
            </div>

            <div className="flex items-center gap-3">
              <input
                type="checkbox"
                id="allowAll"
                checked={allowAll}
                onChange={(e) => setAllowAll(e.target.checked)}
                className="w-4 h-4"
              />
              <label htmlFor="allowAll" className="text-sm text-gray-700 dark:text-gray-300">
                Allow all crawlers (recommended)
              </label>
            </div>

            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="text-sm font-medium text-gray-700 dark:text-gray-300">
                  Disallow Paths
                </label>
                <button
                  onClick={addPath}
                  className="text-sm text-blue-600 hover:text-blue-700"
                >
                  + Add Path
                </button>
              </div>
              <div className="space-y-2">
                {disallowPaths.map((path, index) => (
                  <div key={index} className="flex gap-2">
                    <input
                      type="text"
                      value={path}
                      onChange={(e) => updatePath(index, e.target.value)}
                      placeholder="/path-to-block/"
                      className="flex-1 px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                    />
                    <button
                      onClick={() => removePath(index)}
                      className="px-3 py-2 text-red-600 hover:bg-red-50 rounded-lg"
                    >
                      ✕
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </Card>

        <div className="space-y-4">
          <Card className="p-4 sm:p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">📄 Generated File</h2>
              <div className="flex gap-2">
                <Button onClick={copyToClipboard} size="sm" variant="secondary">
                  {copied ? '✅' : '📋'}
                </Button>
                <Button onClick={downloadFile} size="sm">
                  ⬇️ Download
                </Button>
              </div>
            </div>
            
            <pre className="bg-gray-900 text-green-400 p-4 rounded-lg overflow-x-auto text-sm">
              {generateRobotsTxt()}
            </pre>
          </Card>

          <Card className="p-4 bg-yellow-50 dark:bg-yellow-900/20">
            <h3 className="font-semibold text-yellow-800 dark:text-yellow-300 mb-2">⚠️ Important</h3>
            <ul className="text-sm text-yellow-700 dark:text-yellow-400 space-y-1">
              <li>• Upload this file to your website root (example.com/robots.txt)</li>
              <li>• Test with Google Search Console</li>
              <li>• robots.txt is a suggestion, not a security measure</li>
            </ul>
          </Card>
        </div>
      </div>
    </div>
  );
}
